# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-24 05:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0004_auto_20160621_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_ques', to='questions.Question')),
                ('ques_10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenth_ques', to='questions.Question')),
                ('ques_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sec_ques', to='questions.Question')),
                ('ques_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_ques', to='questions.Question')),
                ('ques_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fourth_ques', to='questions.Question')),
                ('ques_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fifth_ques', to='questions.Question')),
                ('ques_6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sixth_ques', to='questions.Question')),
                ('ques_7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seventh_ques', to='questions.Question')),
                ('ques_8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eigth_ques', to='questions.Question')),
                ('ques_9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ninth_ques', to='questions.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_scored', models.IntegerField(null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='users',
            field=models.ManyToManyField(through='questions.Test', to=settings.AUTH_USER_MODEL),
        ),
    ]
