# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-12 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20160711_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='created_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
